# Generated by Django 2.2.16 on 2022-04-07 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20220407_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/posts', verbose_name='Картинка'),
        ),
    ]
